buidl-labs/crypto-code-school-inside-tezos

FinalContent/ch1-CharacterBuilding/l1-importingLibrary.md
FinalContent/ch1-CharacterBuilding/l2-initializingContract.md
FinalContent/ch1-CharacterBuilding/l3-creatingConstructor.md
FinalContent/ch2-DataTypes/l1-string.md
FinalContent/ch2-DataTypes/l2-integers.md
FinalContent/ch2-DataTypes/l3-boolean&bitwise.md
FinalContent/ch3-CharacterPowers/l1-entry_point.md
FinalContent/ch3-CharacterPowers/l2-functionArguments.md
FinalContent/ch3-CharacterPowers/l3-arithmeticOperators.md
FinalContent/ch4-AdvancedConcept/l1-record.md
FinalContent/ch4-AdvancedConcept/l2-map.md
FinalContent/ch4-AdvancedConcept/l3-spSender.md
FinalContent/ch4-AdvancedConcept/l4-pairs.md
FinalContent/ch4-AdvancedConcept/l5-list.md
FinalContent/ch5-Condition&Assertion/l1-if_else.md
FinalContent/ch5-Condition&Assertion/l2-verify.md
FinalContent/finalCode.py

The Final Content folder contains all the content distributed in various chapters and lessons. The content and code is as per the storyline and examples and tasks are added as well.

Content w.r.t. StoryLine

---

src/templates/chapter.js
src/templates/components/ChapterEditor/index.js
src/utils/compiler.js

Co-authored-by: Suraj Singla <surajsingla333@gmail.com>

feat: add custom validation complier

---

lessons/introduction-to-smartpy/01/01.mdx
lessons/introduction-to-smartpy/02/02.mdx
lessons/introduction-to-smartpy/03/03.mdx
lessons/introduction-to-smartpy/04/04.mdx
lessons/introduction-to-smartpy/06/06.mdx
lessons/introduction-to-smartpy/09/09.mdx
lessons/introduction-to-smartpy/10/10.mdx
lessons/introduction-to-smartpy/11/11.mdx
lessons/introduction-to-smartpy/13/13.mdx
lessons/introduction-to-smartpy/14/14.mdx
lessons/introduction-to-smartpy/15/15.mdx
src/templates/chapter.js
src/templates/chapter.styled.js
src/templates/components/ChapterContent/index.tsx
src/templates/components/ChapterEditor/index.tsx
src/templates/components/ChapterEditor/styled.tsx
src/templates/components/ChapterHeader/index.tsx
src/templates/components/MenuSlider/styled.tsx
src/templates/prism-custom.css

#12, #20, #21, #22, #24 these issues are solved in this commit.

Working on issues #12, #20, #21, #22, #24

---

src/assets/lock.svg
src/components/BackLink/index.js
src/components/BackLink/styled.js
src/components/Footer/index.js
src/components/Footer/styled.js
src/components/PlantGrowthModal/GrownPlant.js
src/components/PlantGrowthModal/Plant.js
src/pages/index.js
src/pages/up-next.js

Implementation of the completion page as per the [figma design](https://www.figma.com/file/hcoRbRF5fZREDTJkLl7cXk/BUIDL-for-Tezos?node-id=536%3A0)
Shows randomly generated plant within up-next page
going to /up-next to check the implementation which can be compared accordingly with the figma design
This pr also makes homeview, chapterview and the completion page mobile responsive
Automatically generates plant and stores it locally
Fixes: cloud animation bug

Ft completion view

---

src/components/PlantGrowthModal/GrownPlant.js

fix: plant render-issue

---

src/PagesStyle/OverviewPage/styled.js
src/assets/completed.svg
src/pages/overview.js
src/templates/chapter.js

Ft store progress locally

---

gatsby-config.js
src/PagesStyle/LandingPage/styled.js
src/components/Seo/index.js
src/pages/index.js
src/pages/overview.js
src/pages/up-next.js
src/templates/chapter.js

Renders appropriate title for every specific page
Also fixes landing page tracking text and refactors landing page style

Basic seo integration

---

lessons/introduction-to-smartpy/01/01.mdx
lessons/introduction-to-smartpy/02/02.mdx
lessons/introduction-to-smartpy/03/03.mdx
lessons/introduction-to-smartpy/04/04.mdx
lessons/introduction-to-smartpy/05/05.mdx
package.json
src/PagesStyle/LandingPage/styled.js
src/PagesStyle/OverviewPage/styled.js
src/components/Footer/index.js
src/components/GameComponents/Storyteller.js
src/pages/tezos/index.js
src/pages/tezos/overview.js

Copy fixes in: landing page, curriculum page, storyteller modal. Small UX fixes to support copy changes
After you've read this notice feel free to remove it.
✄ -----------------------------------------------------------------------------
A clear and concise description of what the PR aims to accomplish.

Copy fixes

---

gatsby-config.js
lessons/introduction-to-smartpy/01/01.mdx
lessons/introduction-to-smartpy/02/02.mdx
lessons/introduction-to-smartpy/03/03.mdx
lessons/introduction-to-smartpy/04/04.mdx
lessons/introduction-to-smartpy/05/05.mdx
lessons/introduction-to-smartpy/06/06.mdx
lessons/introduction-to-smartpy/07/07.mdx
lessons/introduction-to-smartpy/08/08.mdx
lessons/introduction-to-smartpy/09/09.mdx
lessons/introduction-to-smartpy/10/10.mdx
lessons/introduction-to-smartpy/11/11.mdx
lessons/introduction-to-smartpy/12/12.mdx
lessons/introduction-to-smartpy/13/13.mdx
lessons/introduction-to-smartpy/14/14.mdx
src/PagesStyle/OverviewPage/styled.js
src/components/PlantGrowthModal/index.js
src/templates/chapter.js
src/templates/components/ChapterContent/styled.js
src/templates/components/ChapterEditor/index.tsx
src/templates/prism-custom.css
src/utils/compiler.js

After you've read this notice feel free to remove it.
✄ -----------------------------------------------------------------------------
A clear and concise description of what the PR aims to accomplish.

Feature update new curriculum

---

lessons/introduction-to-smartpy/07/07.mdx
src/utils/compiler.js

Content fix in Chapter 7

---

src/utils/compiler.js

Adds intra line white space support

Ft improve custom validation logic

---

gatsby-config.js
src/components/PlantGrowthModal/index.js

Twitter intent on sharing was buggy

fix twitter copy bug

---

lessons/introduction-to-smartpy/10/10.mdx
src/components/PlantGrowthModal/index.js

fix ch10 typo + update new twitter handle

---

lessons/introduction-to-smartpy/13/13.mdx

I'm not sure this is correct, but I was confused by this line so I assume it's supposed to be sp.sender
After you've read this notice feel free to remove it.
✄ -----------------------------------------------------------------------------
A clear and concise description of what the PR aims to accomplish.
Fixes typo in lesson 13

update typo in 13

---

src/html.js

After you've read this notice feel free to remove it.
✄ -----------------------------------------------------------------------------
A clear and concise description of what the PR aims to accomplish.

speed-up-page-load-time

---

.gitignore
gatsby-browser.js
gatsby-config.js
gatsby-ssr.js
package-lock.json
package.json
src/pages/tezos/index.js
src/styles/colors.js
src/styles/spacing.js
src/styles/typography.js

Set up the design system.
Added a `src/styles` folder with colours, spacing, and typography.

Basic stylesheet

---

gatsby-config.js
package-lock.json
package.json
src/components/NavBar/index.js
src/pages/tezos/index.js
tailwind.config.js

* Implements the new navbar.
* Modified `tailwind.config.js` to match our needs.
* `npm start`
@bhaskarSingh please merge this asap, as @harsh242 would need the changes I've made to the `tailwind.config.js` file.

New NavBar + updates to tailwind config

---

src/api.js

🎊 updated API Url

---

src/pages/tezos/profile.js

Makes profile settings read-only.

feat: make profile settings readonly

---

src/pages/tezos/claim-transaction.js
src/pages/tezos/customizebot.js
src/pages/tezos/transaction.js

What does this PR do?
Showing warning message incase user balance is zero or insufficient before buying/claiming a nft cryptobot.

fix: show warning incase balance is insufficient

---

src/pages/tezos/cryptobot.js
src/utils/indexer.js

show owner's xtz address for cryptobtos in profile & marketplace view.
If a bot is not available for sale, owner name doesn’t shows up. I checked the ‘bot’ object it only has seller and no owner.

fix: show nft bot xtz address in profile & marketplace view

---

src/components/Footer/index.js

cookie banner bug fixed

---

src/pages/tezos/academy/index.js
src/templates/overview.js
tailwind.config.js

1. Adds min height to images on academy page, so that the whole page doesn't shift when they load.
2. Removed gray background behind the cryptobot image on the module overview page.

Tiny UI fixes

---

src/pages/tezos/claim-transaction.js
src/utils/indexer.js

1. Show xtz address in marketplace view
2. Show correct view in marketplace view according to bot ownership
3. Show static network fee in claim-transaction view

fix: show bot address & correct view in marketplace

---

src/pages/tezos/marketplace.js
src/pages/tezos/profile.js

Fixes the issue mentioned in #206 by checking if the user is verified or not.

Auth bug for marketplace and profile fixed

---

src/pages/auth.js
src/pages/tezos/customizebot.js
src/templates/components/chapter/NavBar.js

Implements the issue detailed in #224

Issue #224 implemented

---

src/atoms/user-atom.js
src/components/NavBar/index.js
src/pages/tezos/customizebot.js
src/templates/chapter-new.js
src/templates/chapterWithLiveEditor.js
src/templates/components/chapter/NavBar.js
src/utils/automaticLogin.js

Persists auth state beyond refreshes by using the localStorage.
Closes #152
Log in, and then refresh the page. You should automatically see yourself logged in. 
Try this from three different locations - 
1. Index page
2. Customizer
3. Learning Interface

Persist auth state through refreshes

---

src/defaults.js

Updates contract address(deployed on edonet testnet)

feat: update contract address

---

src/templates/components/chapter/LearningInterface.js

Tweaked font sizes for markdown renderer. 
It'll take proper effect when I update the content to use the right headings.
Closes #229

Markdown text sizes tweaked

---

lessons/intro-to-blockchain/01/01.mdx
lessons/intro-to-blockchain/02/02.mdx
lessons/intro-to-blockchain/03/03.mdx
lessons/intro-to-blockchain/04/04.mdx
lessons/intro-to-blockchain/05/05.mdx

Improved course content for `module-0`.
Closes #254

Module-0 content improved

---

gatsby-browser.js
lessons/tokens-FA2/04/04.mdx
src/pages/tezos/customizebot.js
src/templates/components/chapter/LearningInterface.js
src/templates/prism-custom.css

fixes #233

---

gatsby-config.js
package-lock.json
package.json

feat: add sentry

---

src/pages/tezos/profile.js

Load profile view gracefully even if indexer API is down.

fix: load profile view even if indexer api is down

---

gatsby-config.js
src/pages/tezos/claim-transaction.js
src/utils/analytics.js

Add separate amplitude API key for cryptoverse wars beta launch. Resolves #261

feat: add cryptoverse beta amplitude api key

---

src/utils/indexer.js

Fixes marketplace + profile view contract view code.

fix: indexer api fetch logic

---

src/html.js
src/pages/tezos/academy/index.js
src/pages/tezos/claim-transaction.js
src/pages/tezos/customizebot.js
src/templates/chapter-new.js
src/templates/chapter.js
src/templates/chapterWithLiveEditor.js
src/templates/chapterWithLiveEditorOld.js
src/templates/components/chapter/CodingInterface.js
src/templates/overview.js

1. Add `ahref` tracker.
2. Update amplitude event names taxonomy.
3. Updates event name taxonomy for tracking **show answer** click. closes #124

Measure improve

---

src/pages/tezos/claim-transaction.js
src/pages/tezos/transaction.js

Closes #273 
1. Go through the flow of claiming a bot
2. Go through the flow of buying a bot

Stepper UI fix

---

src/pages/tezos/claim-transaction.js
src/pages/tezos/cryptobot/[id].js
src/pages/tezos/transaction.js

guide to getting XTZ links added

---

src/pages/tezos/marketplace.js

Implements the fix, which lets a user access the marketplace without having to log in.
Try accessing `/tezos/marketplace` without being logged in.

Access marketplace without auth

---

src/components/NavBar/index.js

Add warning message that the contract is unaudited.

feat: add warning message

---

src/pages/tezos/customizebot.js

Fixes : When I copy-paste the color codes it doesn't apply or reflect these changes to the bot
https://www.loom.com/share/e5e66b1ec2e24f94b7ccc7b4c3e020e9

Pasting color on color picker input doesnt apply

---

package.json
src/pages/tezos/claim-transaction.js
src/pages/tezos/cryptobot/[id].js
src/pages/tezos/transaction.js
src/styles/global.css

Implements Cryptobot unique URL page design #278

Implement Cryptobot unique URL page design

---

src/components/CryptobotCard/index.js
src/pages/tezos/claim-transaction.js
src/pages/tezos/cryptobot/[id].js
src/pages/tezos/transaction.js
src/styles/global.css

Improves Model Viewer Loader #330

Imporve UX of Model Viewer Loader

---

src/pages/tezos/claim-transaction.js
src/pages/tezos/cryptobot/[id].js
src/pages/tezos/transaction.js

Show Estimated Gas Fee #328 
Note: We are showing static estimate gas fee on all operations

Show gas Fee

---

src/pages/tezos/marketplace.js

#341 
Short-term solution : If the nftList's state is empty we tell the user that the network might be loaded or an indexer issue and ask them to refresh(give a CTA button which refreshes the page)

Nudge User to refresh if marketplace does not loads cryptobots

---

src/html.js

Adds fathom analytics tracking script

fathom script added
